[phases.setup]
nixPkgs = ["nodejs", "python39", "python39Packages.pip", "python39Packages.setuptools", "python39Packages.wheel"]

[phases.install]
cmds = [
  # Install JS dependencies
  "npm ci",
  # Install Python dependencies
  "cd pipecat-service && pip install -r requirements.txt && cd .."
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd pipecat-service && python -m uvicorn main:app --host 0.0.0.0 --port $PIPECAT_PORT & npm start"

[env]
PIPECAT_PORT = "8000"
PIPECAT_SERVICE_URL = "http://localhost:8000"
